export const cmsResources = {
  pages: {
    label: 'Pages',
    endpoint: '/pages',
    columns: ['title', 'path', 'parent_path'],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'path', label: 'Full Path (e.g. /features/solar-design)', type: 'text', required: true },
      { key: 'parent_path', label: 'Parent Path (grid section, e.g. /features)', type: 'text' },
      { key: 'slug', label: 'Slug', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'content', label: 'Content', type: 'textarea' },
      { key: 'image', label: 'Image', type: 'image' },
      { key: 'category', label: 'Category', type: 'text' },
      { key: 'sort_order', label: 'Sort Order', type: 'number' },
      { key: 'is_published', label: 'Published', type: 'checkbox' },
    ],
  },
  regions: {
    label: 'Regions',
    endpoint: '/regions',
    columns: ['name', 'description'],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  countries: {
    label: 'Countries',
    endpoint: '/countries',
    columns: ['name', 'slug', 'region_id'],
    fields: [
      { key: 'region_id', label: 'Region', type: 'select', optionsEndpoint: '/regions', optionLabel: 'name', required: true },
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'slug', label: 'Slug', type: 'text' },
      { key: 'flag', label: 'Flag (emoji or URL)', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  spotlights: {
    label: 'Spotlights',
    endpoint: '/spotlights',
    columns: ['title', 'country_id', 'status'],
    fields: [
      { key: 'country_id', label: 'Country', type: 'select', optionsEndpoint: '/countries', optionLabel: 'name', required: true },
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'content', label: 'Content', type: 'textarea' },
      { key: 'thumbnail', label: 'Image', type: 'image' },
      { key: 'status', label: 'Published', type: 'checkbox' },
    ],
  },
  categories: {
    label: 'Categories',
    endpoint: '/categories',
    columns: ['name', 'slug', 'type'],
    fields: [
      { key: 'name', label: 'Name', type: 'text', required: true },
      { key: 'slug', label: 'Slug', type: 'text' },
      { key: 'type', label: 'Type', type: 'select', options: ['article', 'blog', 'media', 'product'], required: true },
      { key: 'parent_id', label: 'Parent Category', type: 'select', optionsEndpoint: '/categories', optionLabel: 'name' },
    ],
  },
  articles: {
    label: 'Articles',
    endpoint: '/articles',
    columns: ['title', 'status', 'views'],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'slug', label: 'Slug', type: 'text' },
      { key: 'summary', label: 'Summary', type: 'textarea' },
      { key: 'content', label: 'Content', type: 'textarea' },
      { key: 'thumbnail', label: 'Image', type: 'image' },
      { key: 'category_id', label: 'Category', type: 'select', optionsEndpoint: '/categories', optionLabel: 'name' },
      { key: 'country_id', label: 'Country', type: 'select', optionsEndpoint: '/countries', optionLabel: 'name' },
      { key: 'author_id', label: 'Author (User ID)', type: 'select', optionsEndpoint: '/users', optionLabel: 'name' },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'published', 'archived'] },
      { key: 'views', label: 'Views', type: 'number' },
    ],
  },
  features: {
    label: 'Features',
    endpoint: '/features',
    columns: ['title', 'article_id'],
    fields: [
      { key: 'article_id', label: 'Article', type: 'select', optionsEndpoint: '/articles', optionLabel: 'title', required: true },
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'image', label: 'Image', type: 'image' },
    ],
  },
  blogs: {
    label: 'Blogs',
    endpoint: '/blogs',
    columns: ['title', 'status', 'views'],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'slug', label: 'Slug', type: 'text' },
      { key: 'content', label: 'Content', type: 'textarea' },
      { key: 'thumbnail', label: 'Image', type: 'image' },
      { key: 'category_id', label: 'Category', type: 'select', optionsEndpoint: '/categories', optionLabel: 'name' },
      { key: 'author_id', label: 'Author', type: 'select', optionsEndpoint: '/users', optionLabel: 'name' },
      { key: 'status', label: 'Status', type: 'select', options: ['draft', 'published', 'archived'] },
      { key: 'views', label: 'Views', type: 'number' },
    ],
  },
  comments: {
    label: 'Comments',
    endpoint: '/comments',
    columns: ['comment', 'blog_id', 'user_id'],
    fields: [
      { key: 'blog_id', label: 'Blog', type: 'select', optionsEndpoint: '/blogs', optionLabel: 'title', required: true },
      { key: 'user_id', label: 'User', type: 'select', optionsEndpoint: '/users', optionLabel: 'name', required: true },
      { key: 'comment', label: 'Comment', type: 'textarea', required: true },
    ],
  },
  media: {
    label: 'Media',
    endpoint: '/media',
    columns: ['title', 'type', 'duration'],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'type', label: 'Type', type: 'select', options: ['video', 'podcast', 'image'], required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'thumbnail', label: 'Thumbnail', type: 'image' },
      { key: 'media_url', label: 'Media URL', type: 'text' },
      { key: 'duration', label: 'Duration', type: 'text' },
      { key: 'author_id', label: 'Author', type: 'select', optionsEndpoint: '/users', optionLabel: 'name' },
    ],
  },
  publications: {
    label: 'Publications',
    endpoint: '/publications',
    columns: ['title', 'publication_type', 'download_count'],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'publication_type', label: 'Type', type: 'select', options: ['report', 'guideline', 'whitepaper'] },
      { key: 'file_url', label: 'File URL (PDF link)', type: 'text' },
      { key: 'download_count', label: 'Downloads', type: 'number' },
      { key: 'author_id', label: 'Author', type: 'select', optionsEndpoint: '/users', optionLabel: 'name' },
    ],
  },
  bookmarks: {
    label: 'Bookmarks',
    endpoint: '/bookmarks',
    columns: ['user_id', 'article_id'],
    fields: [
      { key: 'user_id', label: 'User', type: 'select', optionsEndpoint: '/users', optionLabel: 'name', required: true },
      { key: 'article_id', label: 'Article', type: 'select', optionsEndpoint: '/articles', optionLabel: 'title', required: true },
    ],
  },
};
